using NUnit.Framework;
using BppLib.Core;
using System.Collections.Generic;

namespace BppLib.Core.Tests
{
    [TestFixture]
    public class ProgramSectionTest
    {
         [Test]
        public void AsBppCodeMethodTest_withVariousBorings()
        {
            var obj = new ProgramSection();
            obj.BiesseEntities.Add(new Bg{IntId=212927420, Id="D8L13", Side=0, Crn="1,4", X=100, Y=100, Z=0, Dp=13, Dia=8});
            obj.BiesseEntities.Add(new Bv{IntId=212926524, Id="D7L19", Side=0, Crn="1,2,4,3", X=9, Y=50, Z=0, Dp=19, Dia=7, Ttp=1});
            obj.BiesseEntities.Add(new Bv{IntId=213245724, Id="D35L12.5", Side=0, Crn="1,4", X=100, Y=22.5, Z=0, Dp=12.5, Dia=35, Ttp=3});
            obj.BiesseEntities.Add(new Bh{IntId=212930620, Id="D8L30", Side=2, Crn="1,4", X=37, Y=0, Z=0, Dp=30, Dia=8, Md=true});
            obj.BiesseEntities.Add(new Bv{IntId=212930044, Id="D15", Side=0, Crn="2,3", X=37, Y=34, Z=0, Dp=13.5, Dia=15});
            obj.BiesseEntities.Add(new Bv{IntId=95864884, Id="D20", Side=0, Crn="1,4", X=9.5, Y=200, Z=0, Dp=14.5, Dia=20});
            string expected = @"[PROGRAM]
@ BG, """", """", 212927420, """", 0 : 0, ""1,4"", 100, 100, 0, 13, 8, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, ""D8L13"", 0, """", """", 0, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BG"", 0, 0, 0, 0, -1, 0, 0, 0
@ BV, """", """", 212926524, """", 0 : 0, ""1,2,4,3"", 9, 50, 0, 19, 7, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, ""D7L19"", 0, """", """", 1, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BV"", 0, 0, 0, 0, -1, 0, 0, 0
@ BV, """", """", 213245724, """", 0 : 0, ""1,4"", 100, 22.5, 0, 12.5, 35, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, ""D35L12.5"", 0, """", """", 3, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BV"", 0, 0, 0, 0, -1, 0, 0, 0
@ BH, """", """", 212930620, """", 0 : 2, ""1,4"", 37, 0, 0, 30, 8, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, -1, ""D8L30"", 0, """", """", 0, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BH"", 0, 0, 0, 0, -1, 0, 0, 0
@ BV, """", """", 212930044, """", 0 : 0, ""2,3"", 37, 34, 0, 13.5, 15, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, ""D15"", 0, """", """", 0, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BV"", 0, 0, 0, 0, -1, 0, 0, 0
@ BV, """", """", 95864884, """", 0 : 0, ""1,4"", 9.5, 200, 0, 14.5, 20, 0, -1, 32, 32, 50, 0, 45, 0, """", 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, ""D20"", 0, """", """", 0, 0, 0, 0, 0, """", 3, 1500, 0, 0, 0, """", """", ""BV"", 0, 0, 0, 0, -1, 0, 0, 0";
            Assert.AreEqual(expected, obj.AsBppCode());
        }

         [Test]
        public void AsCixCodeMethodTest_withVariousBorings()
        {
            var obj = new ProgramSection();
            obj.BiesseEntities.Add(new Bg{IntId=212927420, Id="D8L13", Side=0, Crn="1,4", X=100, Y=100, Z=0, Dp=13, Dia=8});
            obj.BiesseEntities.Add(new Bv{IntId=212926524, Id="D7L19", Side=0, Crn="1,2,4,3", X=9, Y=50, Z=0, Dp=19, Dia=7, Ttp=1});
            obj.BiesseEntities.Add(new Bv{IntId=213245724, Id="D35L12.5", Side=0, Crn="1,4", X=100, Y=22.5, Z=0, Dp=12.5, Dia=35, Ttp=3});
            obj.BiesseEntities.Add(new Bh{IntId=212930620, Id="D8L30", Side=2, Crn="1,4", X=37, Y=0, Z=0, Dp=30, Dia=8, Md=true});
            obj.BiesseEntities.Add(new Bv{IntId=212930044, Id="D15", Side=0, Crn="2,3", X=37, Y=34, Z=0, Dp=13.5, Dia=15});
            obj.BiesseEntities.Add(new Bv{IntId=95864884, Id="D20", Side=0, Crn="1,4", X=9.5, Y=200, Z=0, Dp=14.5, Dia=20});
            string expected = @"
BEGIN MACRO
	NAME=BG
	PARAM,NAME=SIDE,VALUE=0
	PARAM,NAME=CRN,VALUE=""1,4""
	PARAM,NAME=X,VALUE=100
	PARAM,NAME=Y,VALUE=100
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=13
	PARAM,NAME=DIA,VALUE=8
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=NO
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D8L13""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=0
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BG""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO

BEGIN MACRO
	NAME=BV
	PARAM,NAME=SIDE,VALUE=0
	PARAM,NAME=CRN,VALUE=""1,2,4,3""
	PARAM,NAME=X,VALUE=9
	PARAM,NAME=Y,VALUE=50
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=19
	PARAM,NAME=DIA,VALUE=7
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=NO
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D7L19""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=1
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BV""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO

BEGIN MACRO
	NAME=BV
	PARAM,NAME=SIDE,VALUE=0
	PARAM,NAME=CRN,VALUE=""1,4""
	PARAM,NAME=X,VALUE=100
	PARAM,NAME=Y,VALUE=22.5
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=12.5
	PARAM,NAME=DIA,VALUE=35
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=NO
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D35L12.5""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=3
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BV""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO

BEGIN MACRO
	NAME=BH
	PARAM,NAME=SIDE,VALUE=2
	PARAM,NAME=CRN,VALUE=""1,4""
	PARAM,NAME=X,VALUE=37
	PARAM,NAME=Y,VALUE=0
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=30
	PARAM,NAME=DIA,VALUE=8
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=YES
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D8L30""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=0
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BH""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO

BEGIN MACRO
	NAME=BV
	PARAM,NAME=SIDE,VALUE=0
	PARAM,NAME=CRN,VALUE=""2,3""
	PARAM,NAME=X,VALUE=37
	PARAM,NAME=Y,VALUE=34
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=13.5
	PARAM,NAME=DIA,VALUE=15
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=NO
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D15""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=0
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BV""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO

BEGIN MACRO
	NAME=BV
	PARAM,NAME=SIDE,VALUE=0
	PARAM,NAME=CRN,VALUE=""1,4""
	PARAM,NAME=X,VALUE=9.5
	PARAM,NAME=Y,VALUE=200
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=14.5
	PARAM,NAME=DIA,VALUE=20
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RTY,VALUE=rpNO
	PARAM,NAME=DX,VALUE=32
	PARAM,NAME=DY,VALUE=32
	PARAM,NAME=R,VALUE=50
	PARAM,NAME=A,VALUE=0
	PARAM,NAME=DA,VALUE=45
	PARAM,NAME=NRP,VALUE=0
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=AP,VALUE=NO
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=XRC,VALUE=0
	PARAM,NAME=YRC,VALUE=0
	PARAM,NAME=ARP,VALUE=0
	PARAM,NAME=LRP,VALUE=0
	PARAM,NAME=ER,VALUE=YES
	PARAM,NAME=MD,VALUE=NO
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=ID,VALUE=""D20""
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=MAC,VALUE=""""
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=0
	PARAM,NAME=TCL,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=DDS,VALUE=3
	PARAM,NAME=DSP,VALUE=1500
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""BV""
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=DTAS,VALUE=NO
	PARAM,NAME=RMD,VALUE=rmdAuto
	PARAM,NAME=DQT,VALUE=0
	PARAM,NAME=ERDW,VALUE=NO
	PARAM,NAME=DFW,VALUE=0
END MACRO";
            Assert.AreEqual(expected, obj.AsCixCode());
        }
    }
}