using NUnit.Framework;
using BppLib.Core;

namespace BppLib.Core.Tests
{
    [TestFixture]
    public class RoutGTests
    {
       

        [Test]
        public void ChangeIdTest()
        {
            var obj = new RoutG();
            int i = 123456789 ;
            obj.IntId = i ; 
            Assert.AreEqual(i, obj.IntId);
        }

        [Test]
        public void CreateInstanceTest()
        {
            double r = 10.20;
            var obj = new RoutG{Dia = r};
            Assert.AreEqual(r, obj.Dia);
        }

        [Test]
        public void AsBppCodeMethodTest()
        {
           var obj = new RoutG();
            int i = 158591268 ;
            obj.IntId = i ;
            obj.Id = "P1015";
            string expected = "@ ROUTG, \"\", \"\", 158591268, \"\", 0 : \"\", \"P1015\", 0, 0, 10, \"\", 1, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, \"\", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, \"\", 103, 1, 2, 1, 45, 0, 0, 0, 0, 0, 1, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, \"\", 0, 0, 0, 0, 0, 0, 0, 0, 0, \"\", 5, 0, 20, 80, 60, 0, \"\", \"\", \"ROUTG\", 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 99, 0" ;
            Assert.AreEqual(expected, obj.AsBppCode());
        }

        [Test]
        public void AsCixCodeMethodTest()
        {
           var obj = new RoutG();
            int i = 158591268 ;
            obj.IntId = i ;
            obj.Id = "P1015";
            string expected =@"BEGIN MACRO
	NAME=ROUTG
	PARAM,NAME=GID,VALUE=""""
	PARAM,NAME=ID,VALUE=""P1015""
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=Z,VALUE=0
	PARAM,NAME=DP,VALUE=10
	PARAM,NAME=ISO,VALUE=""""
	PARAM,NAME=OPT,VALUE=YES
	PARAM,NAME=DIA,VALUE=18
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=AZ,VALUE=0
	PARAM,NAME=AR,VALUE=0
	PARAM,NAME=ZS,VALUE=0
	PARAM,NAME=ZE,VALUE=0
	PARAM,NAME=CKA,VALUE=azrNO
	PARAM,NAME=THR,VALUE=NO
	PARAM,NAME=RV,VALUE=NO
	PARAM,NAME=CKT,VALUE=NO
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=NU,VALUE=0
	PARAM,NAME=COW,VALUE=NO
	PARAM,NAME=SIL,VALUE=""""
	PARAM,NAME=OVM,VALUE=0
	PARAM,NAME=A21,VALUE=0
	PARAM,NAME=LNG,VALUE=0
	PARAM,NAME=LPR,VALUE=NO
	PARAM,NAME=TOS,VALUE=NO
	PARAM,NAME=VTR,VALUE=0
	PARAM,NAME=DVR,VALUE=0
	PARAM,NAME=OTR,VALUE=0
	PARAM,NAME=SVR,VALUE=0
	PARAM,NAME=COF,VALUE=NO
	PARAM,NAME=DOF,VALUE=0
	PARAM,NAME=GIP,VALUE=YES
	PARAM,NAME=LSV,VALUE=0
	PARAM,NAME=S21,VALUE=-1
	PARAM,NAME=AZS,VALUE=0
	PARAM,NAME=DSP,VALUE=0
	PARAM,NAME=RSP,VALUE=0
	PARAM,NAME=IOS,VALUE=0
	PARAM,NAME=WSP,VALUE=0
	PARAM,NAME=TNM,VALUE=""""
	PARAM,NAME=TTP,VALUE=103
	PARAM,NAME=TCL,VALUE=1
	PARAM,NAME=CRC,VALUE=2
	PARAM,NAME=TIN,VALUE=1
	PARAM,NAME=AIN,VALUE=45
	PARAM,NAME=CIN,VALUE=NO
	PARAM,NAME=GIN,VALUE=0
	PARAM,NAME=TBI,VALUE=NO
	PARAM,NAME=TLI,VALUE=0
	PARAM,NAME=TQI,VALUE=0
	PARAM,NAME=TOU,VALUE=1
	PARAM,NAME=AOU,VALUE=45
	PARAM,NAME=COU,VALUE=NO
	PARAM,NAME=GOU,VALUE=0
	PARAM,NAME=TBO,VALUE=NO
	PARAM,NAME=TLO,VALUE=0
	PARAM,NAME=TQO,VALUE=0
	PARAM,NAME=DIN,VALUE=0
	PARAM,NAME=DOU,VALUE=0
	PARAM,NAME=SDS,VALUE=0
	PARAM,NAME=PRP,VALUE=0
	PARAM,NAME=BDR,VALUE=NO
	PARAM,NAME=SPI,VALUE=""""
	PARAM,NAME=SC,VALUE=NO
	PARAM,NAME=SWI,VALUE=NO
	PARAM,NAME=BLW,VALUE=NO
	PARAM,NAME=PRS,VALUE=NO
	PARAM,NAME=BFC,VALUE=NO
	PARAM,NAME=SHP,VALUE=0
	PARAM,NAME=SWP,VALUE=NO
	PARAM,NAME=CSP,VALUE=0
	PARAM,NAME=UDT,VALUE=NO
	PARAM,NAME=TDT,VALUE=""""
	PARAM,NAME=DDT,VALUE=5
	PARAM,NAME=SDT,VALUE=0
	PARAM,NAME=IDT,VALUE=20
	PARAM,NAME=FDT,VALUE=80
	PARAM,NAME=RDT,VALUE=60
	PARAM,NAME=EA21,VALUE=NO
	PARAM,NAME=CEN,VALUE=""""
	PARAM,NAME=AGG,VALUE=""""
	PARAM,NAME=LAY,VALUE=""ROUTG""
	PARAM,NAME=EECS,VALUE=0
	PARAM,NAME=PDIN,VALUE=1
	PARAM,NAME=PDU,VALUE=1
	PARAM,NAME=PCIN,VALUE=0
	PARAM,NAME=PCU,VALUE=0
	PARAM,NAME=PMOL,VALUE=0
	PARAM,NAME=AUX,VALUE=0
	PARAM,NAME=CRR,VALUE=NO
	PARAM,NAME=NEBS,VALUE=NO
	PARAM,NAME=ETB,VALUE=NO
	PARAM,NAME=FXD,VALUE=NO
	PARAM,NAME=FXDA,VALUE=0
	PARAM,NAME=KDT,VALUE=NO
	PARAM,NAME=EML,VALUE=NO
	PARAM,NAME=ETG,VALUE=NO
	PARAM,NAME=RTAS,VALUE=NO
	PARAM,NAME=RDIN,VALUE=NO
	PARAM,NAME=IMS,VALUE=0
	PARAM,NAME=SDSF,VALUE=0
	PARAM,NAME=INCSTP,VALUE=NO
	PARAM,NAME=ETGT,VALUE=0.1
	PARAM,NAME=AJT,VALUE=NO
	PARAM,NAME=ION,VALUE=NO
	PARAM,NAME=LUBMNZ,VALUE=NO
	PARAM,NAME=SHT,VALUE=spByPost
	PARAM,NAME=SHD,VALUE=0
END MACRO";
            Assert.AreEqual(expected, obj.AsCixCode());
        }
    }
}