using System;
using BppLib.Core;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Globalization;

namespace BppLib.BppParser
{
    public static partial class ParserBpp
    {
		public static Bca ParseBca(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			Bca obj = new Bca();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Dx = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[14]);
			obj.Iso = values[15].Trim().Trim('"');
			obj.Opt =(values[16].Trim() == "1");
			obj.Az = Convert.ToDouble(values[17], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ap =(values[19].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[20]);
			obj.Xrc = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[22], CultureInfo.InvariantCulture);
			obj.Arp = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.Er =(values[25].Trim() == "1");
			obj.Md =(values[26].Trim() == "1");
			obj.Cow =(values[27].Trim() == "1");
			obj.A21 = Convert.ToInt32(values[28]);
			obj.Tos =(values[29].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[30]);
			obj.S21 = Convert.ToInt32(values[31]);
			obj.Id = values[32].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[33], CultureInfo.InvariantCulture);
			obj.Mac = values[34].Trim().Trim('"');
			obj.Tnm = values[35].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[36]);
			obj.Tcl = Convert.ToInt32(values[37]);
			obj.Rsp = Convert.ToInt32(values[38]);
			obj.Ios = Convert.ToInt32(values[39]);
			obj.Wsp = Convert.ToInt32(values[40]);
			obj.Spi = values[41].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Bfc =(values[44].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[45]);
			obj.Ea21 =(values[46].Trim() == "1");
			obj.Cen = values[47].Trim().Trim('"');
			obj.Agg = values[48].Trim().Trim('"');
			obj.Lay = values[49].Trim().Trim('"');
			obj.Prs =(values[50].Trim() == "1");
			obj.Etb =(values[51].Trim() == "1");
			obj.Kdt =(values[52].Trim() == "1");
			obj.Dtas =(values[53].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[54]);
			obj.Dqt = Convert.ToInt32(values[55]);
			obj.Erdw =(values[56].Trim() == "1");
			obj.Dfw = Convert.ToInt32(values[57]);
			return obj;
		}

		public static Bcl ParseBcl(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			Bcl obj = new Bcl();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Dx = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[14]);
			obj.Iso = values[15].Trim().Trim('"');
			obj.Opt =(values[16].Trim() == "1");
			obj.Az = Convert.ToDouble(values[17], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ap =(values[19].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[20]);
			obj.Xrc = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[22], CultureInfo.InvariantCulture);
			obj.Arp = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.Er =(values[25].Trim() == "1");
			obj.Md =(values[26].Trim() == "1");
			obj.Cow =(values[27].Trim() == "1");
			obj.A21 = Convert.ToInt32(values[28]);
			obj.Tos =(values[29].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[30]);
			obj.S21 = Convert.ToInt32(values[31]);
			obj.Id = values[32].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[33], CultureInfo.InvariantCulture);
			obj.Mac = values[34].Trim().Trim('"');
			obj.Tnm = values[35].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[36]);
			obj.Tcl = Convert.ToInt32(values[37]);
			obj.Rsp = Convert.ToInt32(values[38]);
			obj.Ios = Convert.ToInt32(values[39]);
			obj.Wsp = Convert.ToInt32(values[40]);
			obj.Spi = values[41].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Bfc =(values[44].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[45]);
			obj.Ea21 =(values[46].Trim() == "1");
			obj.Cen = values[47].Trim().Trim('"');
			obj.Agg = values[48].Trim().Trim('"');
			obj.Lay = values[49].Trim().Trim('"');
			obj.Prs =(values[50].Trim() == "1");
			obj.Etb =(values[51].Trim() == "1");
			obj.Kdt =(values[52].Trim() == "1");
			obj.Dtas =(values[53].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[54]);
			obj.Dqt = Convert.ToInt32(values[55]);
			obj.Erdw =(values[56].Trim() == "1");
			obj.Dfw = Convert.ToInt32(values[57]);
			return obj;
		}

		public static Bg ParseBg(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			Bg obj = new Bg();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Dx = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[14]);
			obj.Iso = values[15].Trim().Trim('"');
			obj.Opt =(values[16].Trim() == "1");
			obj.Az = Convert.ToDouble(values[17], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ap =(values[19].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[20]);
			obj.Xrc = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[22], CultureInfo.InvariantCulture);
			obj.Arp = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.Er =(values[25].Trim() == "1");
			obj.Md =(values[26].Trim() == "1");
			obj.Cow =(values[27].Trim() == "1");
			obj.A21 = Convert.ToInt32(values[28]);
			obj.Tos =(values[29].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[30]);
			obj.S21 = Convert.ToInt32(values[31]);
			obj.Id = values[32].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[33], CultureInfo.InvariantCulture);
			obj.Mac = values[34].Trim().Trim('"');
			obj.Tnm = values[35].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[36]);
			obj.Tcl = Convert.ToInt32(values[37]);
			obj.Rsp = Convert.ToInt32(values[38]);
			obj.Ios = Convert.ToInt32(values[39]);
			obj.Wsp = Convert.ToInt32(values[40]);
			obj.Spi = values[41].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Bfc =(values[44].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[45]);
			obj.Ea21 =(values[46].Trim() == "1");
			obj.Cen = values[47].Trim().Trim('"');
			obj.Agg = values[48].Trim().Trim('"');
			obj.Lay = values[49].Trim().Trim('"');
			obj.Prs =(values[50].Trim() == "1");
			obj.Etb =(values[51].Trim() == "1");
			obj.Kdt =(values[52].Trim() == "1");
			obj.Dtas =(values[53].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[54]);
			obj.Dqt = Convert.ToInt32(values[55]);
			obj.Erdw =(values[56].Trim() == "1");
			obj.Dfw = Convert.ToInt32(values[57]);
			return obj;
		}

		public static BGeo ParseBGeo(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			BGeo obj = new BGeo();
			obj.IntId = id;
			obj.Gid = values[0].Trim().Trim('"');
			obj.Dp = Convert.ToDouble(values[1], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Thr =(values[3].Trim() == "1");
			obj.Iso = values[4].Trim().Trim('"');
			obj.Opt =(values[5].Trim() == "1");
			obj.Az = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[7], CultureInfo.InvariantCulture);
			obj.Ap =(values[8].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[9]);
			obj.Cow =(values[10].Trim() == "1");
			obj.Sil = values[11].Trim().Trim('"');
			obj.A21 = Convert.ToInt32(values[12]);
			obj.Z = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Tos =(values[14].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[15]);
			obj.S21 = Convert.ToInt32(values[16]);
			obj.Id = values[17].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Mac = values[19].Trim().Trim('"');
			obj.Tnm = values[20].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[21]);
			obj.Tcl = Convert.ToInt32(values[22]);
			obj.Rsp = Convert.ToInt32(values[23]);
			obj.Ios = Convert.ToInt32(values[24]);
			obj.Wsp = Convert.ToInt32(values[25]);
			obj.Spi = values[26].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[27], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[28]);
			obj.Bfc =(values[29].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[30]);
			obj.Ea21 =(values[31].Trim() == "1");
			obj.Cen = values[32].Trim().Trim('"');
			obj.Agg = values[33].Trim().Trim('"');
			obj.Lay = values[34].Trim().Trim('"');
			obj.Prs =(values[35].Trim() == "1");
			obj.Etb =(values[36].Trim() == "1");
			obj.Kdt =(values[37].Trim() == "1");
			obj.Dtas =(values[38].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[39]);
			obj.Dqt = Convert.ToInt32(values[40]);
			return obj;
		}

		public static Bh ParseBh(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			Bh obj = new Bh();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Dx = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[14]);
			obj.Iso = values[15].Trim().Trim('"');
			obj.Opt =(values[16].Trim() == "1");
			obj.Az = Convert.ToDouble(values[17], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ap =(values[19].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[20]);
			obj.Xrc = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[22], CultureInfo.InvariantCulture);
			obj.Arp = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.Er =(values[25].Trim() == "1");
			obj.Md =(values[26].Trim() == "1");
			obj.Cow =(values[27].Trim() == "1");
			obj.A21 = Convert.ToInt32(values[28]);
			obj.Tos =(values[29].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[30]);
			obj.S21 = Convert.ToInt32(values[31]);
			obj.Id = values[32].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[33], CultureInfo.InvariantCulture);
			obj.Mac = values[34].Trim().Trim('"');
			obj.Tnm = values[35].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[36]);
			obj.Tcl = Convert.ToInt32(values[37]);
			obj.Rsp = Convert.ToInt32(values[38]);
			obj.Ios = Convert.ToInt32(values[39]);
			obj.Wsp = Convert.ToInt32(values[40]);
			obj.Spi = values[41].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Bfc =(values[44].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[45]);
			obj.Ea21 =(values[46].Trim() == "1");
			obj.Cen = values[47].Trim().Trim('"');
			obj.Agg = values[48].Trim().Trim('"');
			obj.Lay = values[49].Trim().Trim('"');
			obj.Prs =(values[50].Trim() == "1");
			obj.Etb =(values[51].Trim() == "1");
			obj.Kdt =(values[52].Trim() == "1");
			obj.Dtas =(values[53].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[54]);
			obj.Dqt = Convert.ToInt32(values[55]);
			obj.Erdw =(values[56].Trim() == "1");
			obj.Dfw = Convert.ToInt32(values[57]);
			return obj;
		}

		public static Bv ParseBv(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			Bv obj = new Bv();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Dx = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[14]);
			obj.Iso = values[15].Trim().Trim('"');
			obj.Opt =(values[16].Trim() == "1");
			obj.Az = Convert.ToDouble(values[17], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ap =(values[19].Trim() == "1");
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[20]);
			obj.Xrc = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[22], CultureInfo.InvariantCulture);
			obj.Arp = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.Er =(values[25].Trim() == "1");
			obj.Md =(values[26].Trim() == "1");
			obj.Cow =(values[27].Trim() == "1");
			obj.A21 = Convert.ToInt32(values[28]);
			obj.Tos =(values[29].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[30]);
			obj.S21 = Convert.ToInt32(values[31]);
			obj.Id = values[32].Trim().Trim('"');
			obj.Azs = Convert.ToDouble(values[33], CultureInfo.InvariantCulture);
			obj.Mac = values[34].Trim().Trim('"');
			obj.Tnm = values[35].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[36]);
			obj.Tcl = Convert.ToInt32(values[37]);
			obj.Rsp = Convert.ToInt32(values[38]);
			obj.Ios = Convert.ToInt32(values[39]);
			obj.Wsp = Convert.ToInt32(values[40]);
			obj.Spi = values[41].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Bfc =(values[44].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[45]);
			obj.Ea21 =(values[46].Trim() == "1");
			obj.Cen = values[47].Trim().Trim('"');
			obj.Agg = values[48].Trim().Trim('"');
			obj.Lay = values[49].Trim().Trim('"');
			obj.Prs =(values[50].Trim() == "1");
			obj.Etb =(values[51].Trim() == "1");
			obj.Kdt =(values[52].Trim() == "1");
			obj.Dtas =(values[53].Trim() == "1");
			obj.Rmd =(RmdType)Convert.ToInt32(values[54]);
			obj.Dqt = Convert.ToInt32(values[55]);
			obj.Erdw =(values[56].Trim() == "1");
			obj.Dfw = Convert.ToInt32(values[57]);
			return obj;
		}

		public static S32 ParseS32(string code)
		{
			string[] subs = code.Split(':');
			string[] p1 = subs[0].Split(',');
			int id = Convert.ToInt32(p1[3]);
			string[] values = subs[1].Split(',');
			S32 obj = new S32();
			obj.IntId = id;
			obj.Side = Convert.ToInt32(values[0]);
			obj.Crn = values[1].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Dia = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Thr =(values[7].Trim() == "1");
			obj.Dir =(Direction)Convert.ToInt32(values[8]);
			obj.Stp = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Dst = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.Typ =(SystemBores)Convert.ToInt32(values[11]);
			obj.Iso = values[12].Trim().Trim('"');
			obj.Opt =(values[13].Trim() == "1");
			obj.Xmi = Convert.ToDouble(values[14], CultureInfo.InvariantCulture);
			obj.Cow =(values[15].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[16]);
			obj.Mac = values[17].Trim().Trim('"');
			obj.Tnm = values[18].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[19]);
			obj.Tcl = Convert.ToInt32(values[20]);
			obj.Rsp = Convert.ToInt32(values[21]);
			obj.Ios = Convert.ToInt32(values[22]);
			obj.Wsp = Convert.ToInt32(values[23]);
			obj.Spi = values[24].Trim().Trim('"');
			obj.Dds = Convert.ToDouble(values[25], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[26]);
			obj.Bfc =(values[27].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[28]);
			obj.Ea21 =(values[29].Trim() == "1");
			obj.Cen = values[30].Trim().Trim('"');
			obj.Agg = values[31].Trim().Trim('"');
			obj.Lay = values[32].Trim().Trim('"');
			obj.Prs =(values[33].Trim() == "1");
			obj.Etb =(values[34].Trim() == "1");
			obj.Kdt =(values[35].Trim() == "1");
			obj.Dtas =(values[36].Trim() == "1");
			return obj;
		}

        
    }
}
