using System;
using BppLib.Core;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Globalization;

namespace BppLib.BppParser
{
    public static partial class ParserBpp
    {
		public static GeoText ParseGeoText(string code)
		{
			string[] subs = SplitColon(code);
			string[] p1 = SplitComma(subs[0]);
			int id = Convert.ToInt32(p1[3]);
			string[] values  = SplitComma(subs[1]);
			GeoText obj = new GeoText();
			obj.IntId = id;
			obj.Id = values[0].Trim().Trim('"');
			obj.Side = Convert.ToInt32(values[1]);
			obj.Crn = values[2].Trim().Trim('"');
			obj.Txt = values[3].Trim().Trim('"');
			obj.X = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Y = Convert.ToDouble(values[5], CultureInfo.InvariantCulture);
			obj.Z = Convert.ToDouble(values[6], CultureInfo.InvariantCulture);
			obj.Ang = Convert.ToDouble(values[7], CultureInfo.InvariantCulture);
			obj.Vrs =(TextDirection)Convert.ToInt32(values[8]);
			obj.Aln =(TextAlignment)Convert.ToInt32(values[9]);
			obj.Acc = Convert.ToInt32(values[10]);
			obj.Cir =(values[11].Trim() == "1");
			obj.Rds = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Pst =(TextPosition)Convert.ToInt32(values[13]);
			obj.Fnt = values[14].Trim().Trim('"');
			obj.Sze = Convert.ToDouble(values[15], CultureInfo.InvariantCulture);
			obj.Bol =(values[16].Trim() == "1");
			obj.Itl =(values[17].Trim() == "1");
			obj.Udl =(values[18].Trim() == "1");
			obj.Str =(values[19].Trim() == "1");
			obj.Wgh = Convert.ToDouble(values[20], CultureInfo.InvariantCulture);
			obj.Chs = Convert.ToInt32(values[21]);
			obj.Rty =(Repetition)Convert.ToInt32(values[22]);
			obj.Dx = Convert.ToDouble(values[23], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[24], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[25], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[26], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[27], CultureInfo.InvariantCulture);
			obj.Nrp = Convert.ToInt32(values[28]);
			obj.Xrc = Convert.ToInt32(values[29]);
			obj.Yrc = Convert.ToInt32(values[30]);
			obj.Arp = Convert.ToInt32(values[31]);
			obj.Lrp = Convert.ToInt32(values[32]);
			obj.Er =(values[33].Trim() == "1");
			obj.Rdl =(values[34].Trim() == "1");
			obj.Lay = values[35].Trim().Trim('"');
			return obj;
		}

		public static OffGeo ParseOffGeo(string code)
		{
			string[] subs = SplitColon(code);
			string[] p1 = SplitComma(subs[0]);
			int id = Convert.ToInt32(p1[3]);
			string[] values  = SplitComma(subs[1]);
			OffGeo obj = new OffGeo();
			obj.IntId = id;
			obj.Id = values[0].Trim().Trim('"');
			obj.Gid = values[1].Trim().Trim('"');
			obj.Sil = values[2].Trim().Trim('"');
			obj.Lay = values[3].Trim().Trim('"');
			obj.Ofs = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Shc =(values[5].Trim() == "1");
			obj.Osl =(OffsetSelectionType)Convert.ToInt32(values[6]);
			obj.Ltp =(values[7].Trim() == "1");
			obj.Rv =(values[8].Trim() == "1");
			obj.Crt =(OffsetCompensationType)Convert.ToInt32(values[9]);
			return obj;
		}

		public static Pock ParsePock(string code)
		{
			string[] subs = SplitColon(code);
			string[] p1 = SplitComma(subs[0]);
			int id = Convert.ToInt32(p1[3]);
			string[] values  = SplitComma(subs[1]);
			Pock obj = new Pock();
			obj.IntId = id;
			obj.Gid = values[0].Trim().Trim('"');
			obj.Isl = values[1].Trim().Trim('"');
			obj.Dia = Convert.ToDouble(values[2], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Iso = values[4].Trim().Trim('"');
			obj.Opt =(values[5].Trim() == "1");
			obj.Typ =(PocketType)Convert.ToInt32(values[6]);
			obj.Dlt = Convert.ToDouble(values[7], CultureInfo.InvariantCulture);
			obj.N = Convert.ToInt32(values[8]);
			obj.A = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Tc =(values[10].Trim() == "1");
			obj.Cki =(values[11].Trim() == "1");
			obj.Zst = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.Rv =(values[13].Trim() == "1");
			obj.Rrv =(values[14].Trim() == "1");
			obj.Cow =(values[15].Trim() == "1");
			obj.Ovm = Convert.ToDouble(values[16], CultureInfo.InvariantCulture);
			obj.A21 = Convert.ToInt32(values[17]);
			obj.Z = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Tos =(values[19].Trim() == "1");
			obj.S21 = Convert.ToInt32(values[20]);
			obj.Id = values[21].Trim().Trim('"');
			obj.Dsp = Convert.ToInt32(values[22]);
			obj.Rsp = Convert.ToInt32(values[23]);
			obj.Ios = Convert.ToInt32(values[24]);
			obj.Wsp = Convert.ToInt32(values[25]);
			obj.Tnm = values[26].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[27]);
			obj.Tcl = Convert.ToInt32(values[28]);
			obj.Tin =(LeadInOutType)Convert.ToInt32(values[29]);
			obj.Ain = Convert.ToInt32(values[30]);
			obj.Cin =(values[31].Trim() == "1");
			obj.Tou =(LeadInOutType)Convert.ToInt32(values[32]);
			obj.Aou = Convert.ToInt32(values[33]);
			obj.Cou =(values[34].Trim() == "1");
			obj.Din = Convert.ToDouble(values[35], CultureInfo.InvariantCulture);
			obj.Dou = Convert.ToDouble(values[36], CultureInfo.InvariantCulture);
			obj.Sds = Convert.ToDouble(values[37], CultureInfo.InvariantCulture);
			obj.Prp = Convert.ToInt32(values[38]);
			obj.Spi = values[39].Trim().Trim('"');
			obj.Shp = Convert.ToInt32(values[40]);
			obj.Ea21 =(values[41].Trim() == "1");
			obj.Cen = values[42].Trim().Trim('"');
			obj.Agg = values[43].Trim().Trim('"');
			obj.Lay = values[44].Trim().Trim('"');
			obj.Az = Convert.ToDouble(values[45], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[46], CultureInfo.InvariantCulture);
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[47]);
			obj.Bfc =(values[48].Trim() == "1");
			obj.Etb =(values[49].Trim() == "1");
			obj.Sdsf = Convert.ToInt32(values[50]);
			return obj;
		}

		public static Rout ParseRout(string code)
		{
			string[] subs = SplitColon(code);
			string[] p1 = SplitComma(subs[0]);
			int id = Convert.ToInt32(p1[3]);
			string[] values  = SplitComma(subs[1]);
			Rout obj = new Rout();
			obj.IntId = id;
			obj.Id = values[0].Trim().Trim('"');
			obj.Side = Convert.ToInt32(values[1]);
			obj.Crn = values[2].Trim().Trim('"');
			obj.Z = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Iso = values[5].Trim().Trim('"');
			obj.Opt =(values[6].Trim() == "1");
			obj.Dia = Convert.ToDouble(values[7], CultureInfo.InvariantCulture);
			obj.Rty =(Repetition)Convert.ToInt32(values[8]);
			obj.Xrc = Convert.ToDouble(values[9], CultureInfo.InvariantCulture);
			obj.Yrc = Convert.ToDouble(values[10], CultureInfo.InvariantCulture);
			obj.Dx = Convert.ToDouble(values[11], CultureInfo.InvariantCulture);
			obj.Dy = Convert.ToDouble(values[12], CultureInfo.InvariantCulture);
			obj.R = Convert.ToDouble(values[13], CultureInfo.InvariantCulture);
			obj.A = Convert.ToDouble(values[14], CultureInfo.InvariantCulture);
			obj.Da = Convert.ToDouble(values[15], CultureInfo.InvariantCulture);
			obj.Rdl =(values[16].Trim() == "1");
			obj.Nrp = Convert.ToInt32(values[17]);
			obj.Az = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[19], CultureInfo.InvariantCulture);
			obj.Zs = Convert.ToDouble(values[20], CultureInfo.InvariantCulture);
			obj.Ze = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[22]);
			obj.Thr =(values[23].Trim() == "1");
			obj.Rv =(values[24].Trim() == "1");
			obj.Ckt =(values[25].Trim() == "1");
			obj.Arp = Convert.ToDouble(values[26], CultureInfo.InvariantCulture);
			obj.Lrp = Convert.ToDouble(values[27], CultureInfo.InvariantCulture);
			obj.Er =(values[28].Trim() == "1");
			obj.Cow =(values[29].Trim() == "1");
			obj.Ovm = Convert.ToDouble(values[30], CultureInfo.InvariantCulture);
			obj.A21 = Convert.ToInt32(values[31]);
			obj.Tos =(values[32].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[33]);
			obj.Dvr = Convert.ToDouble(values[34], CultureInfo.InvariantCulture);
			obj.Otr = Convert.ToInt32(values[35]);
			obj.Svr = Convert.ToDouble(values[36], CultureInfo.InvariantCulture);
			obj.Cof =(values[37].Trim() == "1");
			obj.Dof = Convert.ToDouble(values[38], CultureInfo.InvariantCulture);
			obj.Gip =(values[39].Trim() == "1");
			obj.Lsv = Convert.ToInt32(values[40]);
			obj.S21 = Convert.ToInt32(values[41]);
			obj.Azs = Convert.ToDouble(values[42], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[43]);
			obj.Rsp = Convert.ToInt32(values[44]);
			obj.Ios = Convert.ToInt32(values[45]);
			obj.Wsp = Convert.ToInt32(values[46]);
			obj.Tnm = values[47].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[48]);
			obj.Tcl = Convert.ToInt32(values[49]);
			obj.Crc =(ToolCorrection)Convert.ToInt32(values[50]);
			obj.Tin =(LeadInOutType)Convert.ToInt32(values[51]);
			obj.Ain = Convert.ToInt32(values[52]);
			obj.Cin =(values[53].Trim() == "1");
			obj.Gin = Convert.ToDouble(values[54], CultureInfo.InvariantCulture);
			obj.Tbi =(values[55].Trim() == "1");
			obj.Tli = Convert.ToDouble(values[56], CultureInfo.InvariantCulture);
			obj.Tqi = Convert.ToDouble(values[57], CultureInfo.InvariantCulture);
			obj.Tou =(LeadInOutType)Convert.ToInt32(values[58]);
			obj.Aou = Convert.ToInt32(values[59]);
			obj.Cou =(values[60].Trim() == "1");
			obj.Gou = Convert.ToInt32(values[61]);
			obj.Tbo =(values[62].Trim() == "1");
			obj.Tlo = Convert.ToDouble(values[63], CultureInfo.InvariantCulture);
			obj.Tqo = Convert.ToDouble(values[64], CultureInfo.InvariantCulture);
			obj.Din = Convert.ToDouble(values[65], CultureInfo.InvariantCulture);
			obj.Dou = Convert.ToDouble(values[66], CultureInfo.InvariantCulture);
			obj.Sds = Convert.ToDouble(values[67], CultureInfo.InvariantCulture);
			obj.Prp = Convert.ToInt32(values[68]);
			obj.Bdr =(values[69].Trim() == "1");
			obj.Spi = values[70].Trim().Trim('"');
			obj.Sc =(values[71].Trim() == "1");
			obj.Swi =(values[72].Trim() == "1");
			obj.Blw =(values[73].Trim() == "1");
			obj.Prs =(values[74].Trim() == "1");
			obj.Bfc =(values[75].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[76]);
			obj.Swp =(values[77].Trim() == "1");
			obj.Csp = Convert.ToInt32(values[78]);
			obj.Udt =(values[79].Trim() == "1");
			obj.Tdt = values[80].Trim().Trim('"');
			obj.Ddt = Convert.ToDouble(values[81], CultureInfo.InvariantCulture);
			obj.Sdt = Convert.ToDouble(values[82], CultureInfo.InvariantCulture);
			obj.Idt = Convert.ToDouble(values[83], CultureInfo.InvariantCulture);
			obj.Fdt = Convert.ToDouble(values[84], CultureInfo.InvariantCulture);
			obj.Rdt = Convert.ToInt32(values[85]);
			obj.Ea21 =(values[86].Trim() == "1");
			obj.Cen = values[87].Trim().Trim('"');
			obj.Agg = values[88].Trim().Trim('"');
			obj.Lay = values[89].Trim().Trim('"');
			obj.Eecs = Convert.ToInt32(values[90]);
			obj.Pdin = Convert.ToDouble(values[91], CultureInfo.InvariantCulture);
			obj.Pdu = Convert.ToDouble(values[92], CultureInfo.InvariantCulture);
			obj.Pcin = Convert.ToDouble(values[93], CultureInfo.InvariantCulture);
			obj.Pcu = Convert.ToDouble(values[94], CultureInfo.InvariantCulture);
			obj.Pmol = Convert.ToInt32(values[95]);
			obj.Aux = Convert.ToInt32(values[96]);
			obj.Crr =(values[97].Trim() == "1");
			obj.Nebs =(values[98].Trim() == "1");
			obj.Etb =(values[99].Trim() == "1");
			obj.Fxd =(values[100].Trim() == "1");
			obj.Fxda = Convert.ToInt32(values[101]);
			obj.Kdt =(values[102].Trim() == "1");
			obj.Eml =(values[103].Trim() == "1");
			obj.Etg =(values[104].Trim() == "1");
			obj.Rtas =(values[105].Trim() == "1");
			obj.Rdin =(values[106].Trim() == "1");
			obj.Sdsf = Convert.ToInt32(values[107]);
			obj.Incstp =(values[108].Trim() == "1");
			obj.Etgt = Convert.ToDouble(values[109], CultureInfo.InvariantCulture);
			obj.Ajt =(values[110].Trim() == "1");
			obj.Ion =(values[111].Trim() == "1");
			obj.Lubmnz =(values[112].Trim() == "1");
			obj.Sht =(ShtType)Convert.ToInt32(values[113]);
			obj.Shd = Convert.ToInt32(values[114]);
			return obj;
		}

		public static RoutG ParseRoutG(string code)
		{
			string[] subs = SplitColon(code);
			string[] p1 = SplitComma(subs[0]);
			int id = Convert.ToInt32(p1[3]);
			string[] values  = SplitComma(subs[1]);
			RoutG obj = new RoutG();
			obj.IntId = id;
			obj.Gid = values[0].Trim().Trim('"');
			obj.Id = values[1].Trim().Trim('"');
			obj.Z = Convert.ToDouble(values[3], CultureInfo.InvariantCulture);
			obj.Dp = Convert.ToDouble(values[4], CultureInfo.InvariantCulture);
			obj.Iso = values[5].Trim().Trim('"');
			obj.Opt =(values[6].Trim() == "1");
			obj.Dia = Convert.ToDouble(values[7], CultureInfo.InvariantCulture);
			obj.Az = Convert.ToDouble(values[18], CultureInfo.InvariantCulture);
			obj.Ar = Convert.ToDouble(values[19], CultureInfo.InvariantCulture);
			obj.Zs = Convert.ToDouble(values[20], CultureInfo.InvariantCulture);
			obj.Ze = Convert.ToDouble(values[21], CultureInfo.InvariantCulture);
			obj.Cka =(InclinationRotationType)Convert.ToInt32(values[22]);
			obj.Thr =(values[23].Trim() == "1");
			obj.Rv =(values[24].Trim() == "1");
			obj.Ckt =(values[25].Trim() == "1");
			obj.Cow =(values[28].Trim() == "1");
			obj.Sil = values[29].Trim().Trim('"');
			obj.Ovm = Convert.ToDouble(values[30], CultureInfo.InvariantCulture);
			obj.A21 = Convert.ToInt32(values[31]);
			obj.Lng = Convert.ToDouble(values[32], CultureInfo.InvariantCulture);
			obj.Lpr =(values[33].Trim() == "1");
			obj.Tos =(values[34].Trim() == "1");
			obj.Vtr = Convert.ToInt32(values[35]);
			obj.Dvr = Convert.ToDouble(values[36], CultureInfo.InvariantCulture);
			obj.Otr = Convert.ToInt32(values[37]);
			obj.Svr = Convert.ToDouble(values[38], CultureInfo.InvariantCulture);
			obj.Cof =(values[39].Trim() == "1");
			obj.Dof = Convert.ToDouble(values[40], CultureInfo.InvariantCulture);
			obj.Gip =(values[41].Trim() == "1");
			obj.Lsv = Convert.ToInt32(values[42]);
			obj.S21 = Convert.ToInt32(values[43]);
			obj.Azs = Convert.ToDouble(values[44], CultureInfo.InvariantCulture);
			obj.Dsp = Convert.ToInt32(values[45]);
			obj.Rsp = Convert.ToInt32(values[46]);
			obj.Ios = Convert.ToInt32(values[47]);
			obj.Wsp = Convert.ToInt32(values[48]);
			obj.Tnm = values[49].Trim().Trim('"');
			obj.Ttp = Convert.ToInt32(values[50]);
			obj.Tcl = Convert.ToInt32(values[51]);
			obj.Crc =(ToolCorrection)Convert.ToInt32(values[52]);
			obj.Tin =(LeadInOutType)Convert.ToInt32(values[53]);
			obj.Ain = Convert.ToInt32(values[54]);
			obj.Cin =(values[55].Trim() == "1");
			obj.Gin = Convert.ToDouble(values[56], CultureInfo.InvariantCulture);
			obj.Tbi =(values[57].Trim() == "1");
			obj.Tli = Convert.ToDouble(values[58], CultureInfo.InvariantCulture);
			obj.Tqi = Convert.ToDouble(values[59], CultureInfo.InvariantCulture);
			obj.Tou =(LeadInOutType)Convert.ToInt32(values[60]);
			obj.Aou = Convert.ToInt32(values[61]);
			obj.Cou =(values[62].Trim() == "1");
			obj.Gou = Convert.ToInt32(values[63]);
			obj.Tbo =(values[64].Trim() == "1");
			obj.Tlo = Convert.ToDouble(values[65], CultureInfo.InvariantCulture);
			obj.Tqo = Convert.ToDouble(values[66], CultureInfo.InvariantCulture);
			obj.Din = Convert.ToDouble(values[67], CultureInfo.InvariantCulture);
			obj.Dou = Convert.ToDouble(values[68], CultureInfo.InvariantCulture);
			obj.Sds = Convert.ToDouble(values[69], CultureInfo.InvariantCulture);
			obj.Prp = Convert.ToInt32(values[70]);
			obj.Bdr =(values[71].Trim() == "1");
			obj.Spi = values[72].Trim().Trim('"');
			obj.Sc =(values[73].Trim() == "1");
			obj.Swi =(values[74].Trim() == "1");
			obj.Blw =(values[75].Trim() == "1");
			obj.Prs =(values[76].Trim() == "1");
			obj.Bfc =(values[77].Trim() == "1");
			obj.Shp = Convert.ToInt32(values[78]);
			obj.Swp =(values[79].Trim() == "1");
			obj.Csp = Convert.ToInt32(values[80]);
			obj.Udt =(values[81].Trim() == "1");
			obj.Tdt = values[82].Trim().Trim('"');
			obj.Ddt = Convert.ToDouble(values[83], CultureInfo.InvariantCulture);
			obj.Sdt = Convert.ToDouble(values[84], CultureInfo.InvariantCulture);
			obj.Idt = Convert.ToDouble(values[85], CultureInfo.InvariantCulture);
			obj.Fdt = Convert.ToDouble(values[86], CultureInfo.InvariantCulture);
			obj.Rdt = Convert.ToInt32(values[87]);
			obj.Ea21 =(values[88].Trim() == "1");
			obj.Cen = values[89].Trim().Trim('"');
			obj.Agg = values[90].Trim().Trim('"');
			obj.Lay = values[91].Trim().Trim('"');
			obj.Eecs = Convert.ToInt32(values[92]);
			obj.Pdin = Convert.ToDouble(values[93], CultureInfo.InvariantCulture);
			obj.Pdu = Convert.ToDouble(values[94], CultureInfo.InvariantCulture);
			obj.Pcin = Convert.ToDouble(values[95], CultureInfo.InvariantCulture);
			obj.Pcu = Convert.ToDouble(values[96], CultureInfo.InvariantCulture);
			obj.Pmol = Convert.ToInt32(values[97]);
			obj.Aux = Convert.ToInt32(values[98]);
			obj.Crr =(values[99].Trim() == "1");
			obj.Nebs =(values[100].Trim() == "1");
			obj.Etb =(values[101].Trim() == "1");
			obj.Fxd =(values[102].Trim() == "1");
			obj.Fxda = Convert.ToInt32(values[103]);
			obj.Kdt =(values[104].Trim() == "1");
			obj.Eml =(values[105].Trim() == "1");
			obj.Etg =(values[106].Trim() == "1");
			obj.Rtas =(values[107].Trim() == "1");
			obj.Rdin =(values[108].Trim() == "1");
			obj.Ims = Convert.ToInt32(values[109]);
			obj.Sdsf = Convert.ToInt32(values[110]);
			obj.Incstp =(values[111].Trim() == "1");
			obj.Etgt = Convert.ToDouble(values[112], CultureInfo.InvariantCulture);
			obj.Ajt =(values[113].Trim() == "1");
			obj.Ion =(values[114].Trim() == "1");
			obj.Lubmnz =(values[115].Trim() == "1");
			obj.Sht =(ShtType)Convert.ToInt32(values[116]);
			obj.Shd = Convert.ToInt32(values[117]);
			return obj;
		}


    }
}